### PR TITLE
Add support for peek-active_record

### PR DESCRIPTION
**Pull request by wfarr**

### CODE REVIEW

**Comment by dewski** [comment]
Is query reviewer going to be included with this gem? Right now that link won't do anything. If query reviewer will be it's own gem it should be able to wrap `peek-view-mysql2` or `peek-view-pg`:

``` coffeescript
peekMysql = $('#peek-view-mysql2')
queryReviewer = $('<a href="#query_reviewer" class="query_reviewer_toggle"></a>').html(peekMysql.html())
peekMysql.html(queryReviewer)
```

**Comment by wfarr** [comment]
I'd rather not do any DOM insertion with these

**Comment by dewski** [comment]
I just want to make sure each peek view works in isolation, right now adding the link to another view without having the view installed is a bit odd.

**Pull request closed without merging**
